printWidth: 80
tabWidth: 2
useTabs: false
trailingComma: all
endOfLine: lf
proseWrap: always
plugins:
  - "@shopify/prettier-plugin-liquid"
overrides:
  - files: ".github/workflows/*.{yaml,yml}"
    options:
      proseWrap: preserve
