compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnpm

packageExtensions:
  "@rspack/plugin-react-refresh@0.3.6":
    dependencies:
      react-refresh: ">=0.10.0 <1.0.0"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
