enableGlobalCache: true

nodeLinker: pnpm

packageExtensions:
  "@rspack/plugin-react-refresh@0.3.6":
    dependencies:
      react-refresh: ">=0.10.0 <1.0.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
