FROM node:18-alpine
ENV NODE_ENV=production
RUN apk add --no-cache libc6-compat curl
WORKDIR /app
COPY . .
EXPOSE 502
EXPOSE 1883
EXPOSE 80
EXPOSE 443
RUN yarn --frozen-lockfile
CMD yarn dev:publishing