FROM node:18-alpine
ENV NODE_ENV=production
RUN apk add --no-cache libc6-compat
COPY . /build
WORKDIR /build
RUN yarn --frozen-lockfile
RUN yarn build:publishing

FROM node:18-alpine
ENV NODE_ENV=production
RUN apk add --no-cache libc6-compat curl
COPY --from=0 /build/src/Mess.Publishing/dist /run
WORKDIR /run/dist
EXPOSE 502
EXPOSE 1883
EXPOSE 80
EXPOSE 443
CMD ./dist/publishing
