version: "3.8"

services:
  postgres:
    image: timescale/timescaledb-ha:${POSTGRES_VERSION}
    restart: always
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    mem_limit: ${POSTGRES_MEMLIMIT}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local
