# shellcheck disable=SC2034

export OrchardCore__OrchardCore_AutoSetup__Tenants__0__AdminUsername="admin"
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__AdminEmail="admin@admin.com"
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__AdminPassword="admin"
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__DatabaseProvider="Postgres"
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__DatabaseConnectionString="Server=localhost;Port=5432;User Id=mess;Password=mess;Database=mess",
export OrchardCore__OrchardCore_AutoSetup__Tenants__0__DatabaseTablePrefix="ozds"
