namespace Mess.Ozds.Abstractions.Timeseries;

public record AbbMeasurement(
  string Tenant,
  string DeviceId,
  DateTimeOffset Timestamp,
  decimal? VoltageL1_V,
  decimal? VoltageL2_V,
  decimal? VoltageL3_V,
  decimal? CurrentL1_A,
  decimal? CurrentL2_A,
  decimal? CurrentL3_A,
  decimal? ActivePowerTotal_W,
  decimal? ActivePowerL1_W,
  decimal? ActivePowerL2_W,
  decimal? ActivePowerL3_W,
  decimal? ReactivePowerTotal_VAR,
  decimal? ReactivePowerL1_VAR,
  decimal? ReactivePowerL2_VAR,
  decimal? ReactivePowerL3_VAR,
  decimal? ApparentPowerTotal_VA,
  decimal? ApparentPowerL1_VA,
  decimal? ApparentPowerL2_VA,
  decimal? ApparentPowerL3_VA,
  decimal? PowerFactorTotal,
  decimal? PowerFactorL1,
  decimal? PowerFactorL2,
  decimal? PowerFactorL3,
  decimal? ActiveEnergyImportTotal_kWh,
  decimal? ActiveEnergyExportTotal_kWh,
  decimal? ActiveEnergyNetTotal_kWh,
  decimal? ActiveEnergyImportTariff1_kWh,
  decimal? ActiveEnergyImportTariff2_kWh,
  decimal? ActiveEnergyExportTariff1_kWh,
  decimal? ActiveEnergyExportTariff2_kWh
);
