namespace Mess.Ozds.Iot;

public record AbbPushRequest(
  decimal VoltageL1_V,
  decimal VoltageL2_V,
  decimal VoltageL3_V,
  decimal CurrentL1_A,
  decimal CurrentL2_A,
  decimal CurrentL3_A,
  decimal ActivePowerL1_W,
  decimal ActivePowerL2_W,
  decimal ActivePowerL3_W,
  decimal ReactivePowerL1_VAR,
  decimal ReactivePowerL2_VAR,
  decimal ReactivePowerL3_VAR,
  decimal ActivePowerImportL1_Wh,
  decimal ActivePowerImportL2_Wh,
  decimal ActivePowerImportL3_Wh,
  decimal ActivePowerExportL1_Wh,
  decimal ActivePowerExportL2_Wh,
  decimal ActivePowerExportL3_Wh,
  decimal ReactivePowerImportL1_VARh,
  decimal ReactivePowerImportL2_VARh,
  decimal ReactivePowerImportL3_VARh,
  decimal ReactivePowerExportL1_VARh,
  decimal ReactivePowerExportL2_VARh,
  decimal ReactivePowerExportL3_VARh,
  decimal ActiveEnergyImportTotal_Wh,
  decimal ActiveEnergyExportTotal_Wh,
  decimal ReactiveEnergyImportTotal_VARh,
  decimal ReactiveEnergyExportTotal_VARh
);
