[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "c-sharp"
formatter = { command = "dotnet", args = [ "csharpier" ] }
language-server = { command = "OmniSharp", args = [ "-lsp" ], timeout = 10000 }
auto-format = true

[[language]]
name = "typescript"
language-server = { command = "bunx --bun typescript-language-server", args = [ "--stdio" ], config.hostInfo = "helix" }
formatter = { command = "bunx --bun prettier" }
auto-format = true

[[language]]
name = "javascript"
language-server = { command = "bunx --bun typescript-language-server", args = [ "--stdio" ], config.hostInfo = "helix" }
formatter = { command = "bunx --bun prettier" }
auto-format = true

[[language]]
name = "css"
language-server = { command = "bunx --bun vscode-css-language-server", args = ["--stdio"], config = { provideFormatter = true, css = { validate = { enable = true } } } }
formatter = { command = "bunx --bun prettier" }
auto-format = true

[[language]]
name = "scss"
language-server = { command = "bunx --bun vscode-css-language-server", args = ["--stdio"], config = { provideFormatter = true, css = { validate = { enable = true } } } }
formatter = { command = "bunx --bun prettier" }
auto-format = true

[[language]]
name = "yaml"
language-server = { command = "bunx --bun yaml-language-server", args = ["--stdio"] }
formatter = { command = "bunx --bun prettier" }
auto-format = true
