[[language]]
name = "c-sharp"
formatter = { command = "dotnet", args = [ "csharpier" ] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "yarn prettier" }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "yarn prettier" }
auto-format = true

[[language]]
name = "css"
formatter = { command = "yarn prettier" }
auto-format = true

[[language]]
name = "scss"
formatter = { command = "yarn prettier" }
auto-format = true
