[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "c-sharp"
formatter = { command = "dotnet", args = [ "csharpier" ] }
language-server = { command = "OmniSharp", args = [ "-lsp" ], timeout = 10000 }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "yarn prettier" }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "yarn prettier" }
auto-format = true

[[language]]
name = "css"
formatter = { command = "yarn prettier" }
auto-format = true

[[language]]
name = "scss"
formatter = { command = "yarn prettier" }
auto-format = true
