#!/usr/bin/env sh

abs() { echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"; }
HUSKY_DIR="$(dirname "$(abs "$0")")"
ROOT_DIR="$(dirname "$HUSKY_DIR")"
SCRIPT_DIR="$ROOT_DIR/scripts"

. "$HUSKY_DIR/_/husky.sh"

"$SCRIPT_DIR/lint.sh"
