// <auto-generated />
using System;
using Mess.Timeseries.Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mess.Migrations.Timescale
{
    [DbContext(typeof(TimeseriesContext))]
    partial class TimeseriesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mess.Timeseries.Entities.Measurement", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .HasColumnType("varchar");

                    b.Property<float>("Power")
                        .HasColumnType("float");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<float>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Timestamp", "SourceId");

                    b.ToTable("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
