# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version-file: .nvmrc
#       - uses: actions/setup-dotnet@v3
#         with:
#           global-json-file: global.json

#       - name: prepare
#         run: ./mess prepare --skip test
#       - name: publish
#         run: ./mess publish --publish-dir ${{env.DOTNET_ROOT}}/myapp

#       - name: upload
#         uses: actions/upload-artifact@v2
#         with:
#           name: .net-app
#           path: ${{env.DOTNET_ROOT}}/myapp

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: "Production"
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#     steps:
#       - name: download
#         uses: actions/download-artifact@v2
#         with:
#           name: .net-app
#       - name: deploy
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: "altibiz-mess"
#           slot-name: "Production"
#           # prettier-ignore
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4416F6604DF04E9BB6F36F3413BC3CCB }}
#           package: .
